brew "bat"
brew "curl"
brew "doggo"
brew "eza"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "imagemagick"
brew "lazygit"
brew "mas"
brew "mise"
brew "ripgrep"
brew "starship"
brew "stow"
brew "trash"
brew "wget"
brew "yazi"
brew "zoxide"
brew "zsh"
cask "1password"
# cask "acorn"
# cask "docker"
cask "figma"
cask "firefox@developer-edition"
cask "font-blex-mono-nerd-font"
cask "font-geist-mono-nerd-font"
cask "font-im-writing-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-monaspace-nerd-font"
cask "font-sauce-code-pro-nerd-font"
cask "ghostty"
cask "github"
cask "google-chrome"
# cask "handbrake"
# cask "iina"
# cask "onyx"
cask "raycast"
# cask "steermouse"
cask "visual-studio-code"
# cask "zed"
# cask "zoom"
# mas "1Blocker", id: 1365531024
# mas "1Password for Safari", id: 1569813296
# mas "Affinity Designer 2", id: 1616831348
# mas "Affinity Photo 2", id: 1616822987
# mas "Googly Eyes", id: 6743048714
# mas "Harvest", id: 506189836
# mas "Keynote", id: 409183694
# mas "Shareful", id: 1522267256
# mas "Tailscale", id: 1475387142
# mas "Things", id: 904280696
# mas "Unread", id: 1363637349
# mas "Velja", id: 1607635845
# vscode "aaron-bond.better-comments"
# vscode "albert.tabout"
# vscode "astro-build.astro-vscode"
# vscode "bierner.comment-tagged-templates"
# vscode "biomejs.biome"
# vscode "bradlc.vscode-tailwindcss"
# vscode "britesnow.vscode-toggle-quotes"
# vscode "catppuccin.catppuccin-vsc"
# vscode "catppuccin.catppuccin-vsc-icons"
# vscode "christian-kohler.npm-intellisense"
# vscode "davidanson.vscode-markdownlint"
# vscode "dbaeumer.vscode-eslint"
# vscode "eamodio.gitlens"
# vscode "editorconfig.editorconfig"
# vscode "esbenp.prettier-vscode"
# vscode "fabiospampinato.vscode-banal"
# vscode "formulahendry.auto-rename-tag"
# vscode "github.copilot"
# vscode "github.copilot-chat"
# vscode "graphql.vscode-graphql-syntax"
# vscode "gruntfuggly.todo-tree"
# vscode "jkjustjoshing.vscode-text-pastry"
# vscode "jock.svg"
# vscode "joshpayette.cycle-comment-styles"
# vscode "kisstkondoros.vscode-gutter-preview"
# vscode "mikestead.dotenv"
# vscode "mrmlnc.vscode-duplicate"
# vscode "ms-playwright.playwright"
# vscode "ms-vscode.live-server"
# vscode "ms-vsliveshare.vsliveshare"
# vscode "naumovs.color-highlight"
# vscode "orta.vscode-twoslash-queries"
# vscode "paulshen.paul-typescript-toolkit"
# vscode "phoenisx.cssvar"
# vscode "redhat.vscode-yaml"
# vscode "ritwickdey.liveserver"
# vscode "sdras.night-owl"
# vscode "stkb.rewrap"
# vscode "streetsidesoftware.code-spell-checker"
# vscode "stripe.markdoc-language-support"
# vscode "tamasfe.even-better-toml"
# vscode "tamj0rd2.ts-quickfixes-extension"
# vscode "tobermory.es6-string-html"
# vscode "unifiedjs.vscode-mdx"
# vscode "wix.vscode-import-cost"
# vscode "wmaurer.change-case"
# vscode "yzhang.markdown-all-in-one"
